[tool.poetry]
name = "lumen-api"
version = "0.1.0"
description = "API for Lumen"
authors = ["Agustin Paya <payaagustin@gmail.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
django = "^6.0"
django-ninja = "^1.5"
django-cors-headers = "^4.9"
dj-database-url = "^3.0"
python-dotenv = "^1.2"
whitenoise = "^6.11"
psycopg2-binary = "^2.9"
google-api-python-client = "^2.187"
google-auth-httplib2 = "^0.3"
google-auth-oauthlib = "^1.2"
requests = "^2.32"
gunicorn = "^21.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "ruff (>=0.14.14,<0.15.0)",
    "pytest (>=9.0.2,<10.0.0)",
    "pytest-django (>=4.11.1,<5.0.0)"
]

[tool.ruff]
line-length = 88
exclude = [
    ".git",
    ".ruff_cache",
    ".venv",
    "__pypackages__",
    "migrations",
]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "lumen.settings"
python_files = ["tests.py", "test_*.py", "*_tests.py"]
